# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/edouard/Projects/CL-server/core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/edouard/Projects/CL-server/core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edouard/Projects/CL-server/core/CMakeFiles /home/edouard/Projects/CL-server/core/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edouard/Projects/CL-server/core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/core/Interfaces/DB.o: src/core/Interfaces/DB.cpp.o

.PHONY : src/core/Interfaces/DB.o

# target to build an object file
src/core/Interfaces/DB.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Interfaces/DB.cpp.o
.PHONY : src/core/Interfaces/DB.cpp.o

src/core/Interfaces/DB.i: src/core/Interfaces/DB.cpp.i

.PHONY : src/core/Interfaces/DB.i

# target to preprocess a source file
src/core/Interfaces/DB.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Interfaces/DB.cpp.i
.PHONY : src/core/Interfaces/DB.cpp.i

src/core/Interfaces/DB.s: src/core/Interfaces/DB.cpp.s

.PHONY : src/core/Interfaces/DB.s

# target to generate assembly for a file
src/core/Interfaces/DB.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Interfaces/DB.cpp.s
.PHONY : src/core/Interfaces/DB.cpp.s

src/core/Models/Path.o: src/core/Models/Path.cpp.o

.PHONY : src/core/Models/Path.o

# target to build an object file
src/core/Models/Path.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Path.cpp.o
.PHONY : src/core/Models/Path.cpp.o

src/core/Models/Path.i: src/core/Models/Path.cpp.i

.PHONY : src/core/Models/Path.i

# target to preprocess a source file
src/core/Models/Path.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Path.cpp.i
.PHONY : src/core/Models/Path.cpp.i

src/core/Models/Path.s: src/core/Models/Path.cpp.s

.PHONY : src/core/Models/Path.s

# target to generate assembly for a file
src/core/Models/Path.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Path.cpp.s
.PHONY : src/core/Models/Path.cpp.s

src/core/Models/PathPoint.o: src/core/Models/PathPoint.cpp.o

.PHONY : src/core/Models/PathPoint.o

# target to build an object file
src/core/Models/PathPoint.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/PathPoint.cpp.o
.PHONY : src/core/Models/PathPoint.cpp.o

src/core/Models/PathPoint.i: src/core/Models/PathPoint.cpp.i

.PHONY : src/core/Models/PathPoint.i

# target to preprocess a source file
src/core/Models/PathPoint.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/PathPoint.cpp.i
.PHONY : src/core/Models/PathPoint.cpp.i

src/core/Models/PathPoint.s: src/core/Models/PathPoint.cpp.s

.PHONY : src/core/Models/PathPoint.s

# target to generate assembly for a file
src/core/Models/PathPoint.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/PathPoint.cpp.s
.PHONY : src/core/Models/PathPoint.cpp.s

src/core/Models/Point.o: src/core/Models/Point.cpp.o

.PHONY : src/core/Models/Point.o

# target to build an object file
src/core/Models/Point.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Point.cpp.o
.PHONY : src/core/Models/Point.cpp.o

src/core/Models/Point.i: src/core/Models/Point.cpp.i

.PHONY : src/core/Models/Point.i

# target to preprocess a source file
src/core/Models/Point.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Point.cpp.i
.PHONY : src/core/Models/Point.cpp.i

src/core/Models/Point.s: src/core/Models/Point.cpp.s

.PHONY : src/core/Models/Point.s

# target to generate assembly for a file
src/core/Models/Point.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Point.cpp.s
.PHONY : src/core/Models/Point.cpp.s

src/core/Models/Segment.o: src/core/Models/Segment.cpp.o

.PHONY : src/core/Models/Segment.o

# target to build an object file
src/core/Models/Segment.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Segment.cpp.o
.PHONY : src/core/Models/Segment.cpp.o

src/core/Models/Segment.i: src/core/Models/Segment.cpp.i

.PHONY : src/core/Models/Segment.i

# target to preprocess a source file
src/core/Models/Segment.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Segment.cpp.i
.PHONY : src/core/Models/Segment.cpp.i

src/core/Models/Segment.s: src/core/Models/Segment.cpp.s

.PHONY : src/core/Models/Segment.s

# target to generate assembly for a file
src/core/Models/Segment.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Models/Segment.cpp.s
.PHONY : src/core/Models/Segment.cpp.s

src/core/main.o: src/core/main.cpp.o

.PHONY : src/core/main.o

# target to build an object file
src/core/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/main.cpp.o
.PHONY : src/core/main.cpp.o

src/core/main.i: src/core/main.cpp.i

.PHONY : src/core/main.i

# target to preprocess a source file
src/core/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/main.cpp.i
.PHONY : src/core/main.cpp.i

src/core/main.s: src/core/main.cpp.s

.PHONY : src/core/main.s

# target to generate assembly for a file
src/core/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/main.cpp.s
.PHONY : src/core/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... src/core/Interfaces/DB.o"
	@echo "... src/core/Interfaces/DB.i"
	@echo "... src/core/Interfaces/DB.s"
	@echo "... src/core/Models/Path.o"
	@echo "... src/core/Models/Path.i"
	@echo "... src/core/Models/Path.s"
	@echo "... src/core/Models/PathPoint.o"
	@echo "... src/core/Models/PathPoint.i"
	@echo "... src/core/Models/PathPoint.s"
	@echo "... src/core/Models/Point.o"
	@echo "... src/core/Models/Point.i"
	@echo "... src/core/Models/Point.s"
	@echo "... src/core/Models/Segment.o"
	@echo "... src/core/Models/Segment.i"
	@echo "... src/core/Models/Segment.s"
	@echo "... src/core/main.o"
	@echo "... src/core/main.i"
	@echo "... src/core/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

